### ISSUE TITLE
I updates the package.json file to the newest dev packages and now it fails.

### ISSUE THREAD

**Issue by ChristianOConnor** [chevalvert/boilerplate-php-webpack#3]
This is my new package.json file.  
```
{
  "name": "boilerplate-php-webpack",
  "version": "0.0.1",
  "description": "boilerplate for PHP-based websites",
  "scripts": {
    "start": "cross-env NODE_ENV=development node scripts/webpack-serve.js",
    "build": "cross-env NODE_ENV=production npm run test && cross-env NODE_ENV=production node scripts/webpack-build.js",
    "build:preprod": "cross-env NODE_ENV=preprod node scripts/webpack-build.js",
    "lint": "npm run lint:js && npm run lint:css",
    "lint:js": "eslint --ext .js ./config ./scripts ./src --cache",
    "lint:css": "stylelint ./src/**/*.scss ./src/**/*.css --cache",
    "test": "ava --verbose"
  },
  "aliases": {},
  "author": "Arnaud Juracek",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "@babel/preset-env": "^7.15.0",
    "@babel/runtime": "^7.15.0",
    "@pqml/node-php-server": "^0.5.0",
    "autoprefixer": "^10.3.3",
    "ava": "^3.15.0",
    "babel-loader": "^8.2.2",
    "browser-sync": "^2.27.5",
    "cross-env": "^7.0.3",
    "css-loader": "^6.2.0",
    "eslint": "^7.32.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.24.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "esm": "^3.2.25",
    "file-loader": "^6.2.0",
    "fs-extra": "^10.0.0",
    "kool-shell": "^2.1.0",
    "node-sass": "^6.0.1",
    "postcss-loader": "^6.1.1",
    "progress-bar-webpack-plugin": "^2.1.0",
    "resolve-url-loader": "^4.0.0",
    "sass-loader": "^12.1.0",
    "style-loader": "^3.2.1",
    "stylelint": "^13.13.1",
    "stylelint-order": "^4.1.0",
    "stylelint-scss": "^3.20.1",
    "tail": "^2.2.3",
    "webpack": "^5.51.1",
    "webpack-dev-middleware": "^5.0.0",
    "webpack-hot-middleware": "^2.25.0",
    "webpack-merge": "^5.8.0",
    "worker-loader": "^3.0.8"
  },
  "dependencies": {},
  "private": true
}
```  
  
also, I changed line 1 of config/webpack.config.dev.js to `const { merge } = require('webpack-merge')` note the {} around "merge."  
  
When I try to start the project with `npm start`, I get:  
```
npm start

> boilerplate-php-webpack@0.0.1 start
> cross-env NODE_ENV=development node scripts/webpack-serve.js


[1/3] Starting a php server...
⚠️  Built-in PHP will be removed from future versions of macOS
[PHP] Server started on localhost:35410
PHP Server started on localhost:35410

⚠️  Warning:
On MacOS / OSX, Node can't reach PHP built-in server through localhost.
Proxying [::1]:35410 instead.

[2/3] Running the webpack compiler...
/Users/<myusername>/path/to/this/dir/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105
    throw new _ValidationError.default(errors, schema, configuration);
    ^

ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.
    at validate (/Users/<myusername>/path/to/this/dir/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at validateSchema (/Users/<myusername>/path/to/this/dir/node_modules/webpack/lib/validateSchema.js:78:2)
    at create (/Users/<myusername>/path/to/this/dir/node_modules/webpack/lib/webpack.js:109:24)
    at webpack (/Users/<myusername>/path/to/this/dir/node_modules/webpack/lib/webpack.js:151:32)
    at f (/Users/<myusername>/path/to/this/dir/node_modules/webpack/lib/index.js:55:16)
    at webpackInit (/Users/<myusername>/path/to/this/dir/scripts/webpack-serve.js:85:14)
    at EventEmitter.<anonymous> (/Users/<myusername>/path/to/this/dir/scripts/webpack-serve.js:75:5)
    at EventEmitter.emit (node:events:394:28)
    at Timeout._onTimeout (/Users/<myusername>/path/to/this/dir/node_modules/@pqml/node-php-server/src/server.js:159:17)
    at listOnTimeout (node:internal/timers:557:17) {
  errors: [
    {
      keyword: 'anyOf',
      dataPath: '.devtool',
      schemaPath: '#/definitions/DevTool/anyOf',
      params: {},
      message: 'should match some schema in anyOf',
      schema: [
        { enum: [ false, 'eval' ] },
        {
          type: 'string',
          pattern: '^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$'
        }
      ],
      parentSchema: {
        description: 'A developer tool to enhance debugging (false | eval | [inline-|hidden-|eval-][nosources-][cheap-[module-]]source-map).',
        anyOf: [
          { enum: [Array] },
          {
            type: 'string',
            pattern: '^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$'
          }
        ]
      },
      data: '#eval-source-map',
      children: [
        {
          keyword: 'enum',
          dataPath: '.devtool',
          schemaPath: '#/definitions/DevTool/anyOf/0/enum',
          params: { allowedValues: [Array] },
          message: 'should be equal to one of the allowed values',
          schema: [ false, 'eval' ],
          parentSchema: { enum: [Array] },
          data: '#eval-source-map',
          children: undefined
        },
        {
          keyword: 'pattern',
          dataPath: '.devtool',
          schemaPath: '#/definitions/DevTool/anyOf/1/pattern',
          params: {
            pattern: '^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$'
          },
          message: 'should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$"',
          schema: '^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$',
          parentSchema: {
            type: 'string',
            pattern: '^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$'
```  
  
And much more text after that detailing the error.  
  
What do you think the problem is?

**Comment by arnaudjuracek** [comment]
The error message is pretty self explanatory, your configuration does not match what Webpack expects it to be.
You upgraded from Webpack 4.x to 5.x, so I suggest you refer to the [Webpack migration guide](https://webpack.js.org/migrate/5/), and prepare to enter the npm dependency hell. Or just stick to the latest Webpack 4.x minor version.

Good luck !
